[Thu Oct 17 14:01:31 2019] [Out]: Args: ['C:/Users/quint/Documents/GitHub/QplayBubbles-Releaes/__main__.py', 'v1.5.1-pre5', 'v1_5_1_pre5', '16']
[Thu Oct 17 14:01:31 2019] [Out]: Launcher Path: C:\Users\quint\Documents
[Thu Oct 17 14:01:31 2019] [Out]: {'bubble': {'chance': 10, 'max-radius': 30, 'min-radius': 21, 'max-speed': 4.8, 'base-speed': 4.8, 'screen-gap': 100}, 'game': {'level-score': 10000, 'time-limit': 90, 'pause': False, 'resolution': '1920x1080', 'ship-radius': 15, 'ship-speed': 10, 'fullscreen': True, 'language': 'en'}, 'font': {'family': 'helvetica', 'size': -9}}
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-566:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-521:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-485:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-536:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-503:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-587:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-593:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-494:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-500:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-584:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-539:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-578:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-533:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-482:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-497:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-572:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-509:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-524:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-518:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-527:
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-569:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-554:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-563:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-581:
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-590:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-530:
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-548:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-592:
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-575:
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-557:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-488:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-551:
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-506:
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-515:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-542:
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-545:
:
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-512:
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-491:
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]: Exception in thread Thread-560:
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:     self.run()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target([Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>

[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBu[Thu Oct 17 14:01:35 2019] [Err]:     self._target([Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 54, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\t[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 25[Thu Oct 17 14:01:35 2019] [Err]:     Thread(None, lambda: self.background.move_bubbles()).start()
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 98, in create_bubble
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 126, in move_bubbles
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     y = randint(int(r), int(self._canvas.winfo_height() - r))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
ckages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self._canvas.move(self.__bubbles[index], -self.__speed[index], 0)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1000, in winfo_height
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2591, in move
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call('winfo', 'height', self._w))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-package[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     self.tk.call((self._w, 'move') + args)
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-package[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
s\threadsafe_tkinter\__init__.py", line 133, in process_requests
safe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
safe
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
uint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
ackages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
hreadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:     raise result
[Thu Oct 17 14:01:35 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]: 
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:35 2019] [Err]: 
[Thu Oct 17 14:01:35 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:35 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:35 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:35 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:36 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:36 2019] [Err]: 
kinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]:     response[:] = (func(*a, **kw), False)
canvas"
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: bad window path name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
[Thu Oct 17 14:01:36 2019] [Err]: 
