[Thu Oct 17 14:12:23 2019] [Out]: Args: ['C:/Users/quint/Documents/GitHub/QplayBubbles-Releaes/__main__.py', 'v1.5.1-pre5', 'v1_5_1_pre5', '16']
[Thu Oct 17 14:12:23 2019] [Out]: Launcher Path: C:\Users\quint\Documents
[Thu Oct 17 14:12:23 2019] [Out]: {'bubble': {'chance': 10, 'max-radius': 30, 'min-radius': 21, 'max-speed': 4.8, 'base-speed': 4.8, 'screen-gap': 100}, 'game': {'level-score': 10000, 'time-limit': 90, 'pause': False, 'resolution': '1920x1080', 'ship-radius': 15, 'ship-speed': 10, 'fullscreen': True, 'language': 'en'}, 'font': {'family': 'helvetica', 'size': -9}}
[Thu Oct 17 14:12:42 2019] [Err]: Exception in thread Thread-32861:
[Thu Oct 17 14:12:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:12:42 2019] [Err]:     self.run()
[Thu Oct 17 14:12:42 2019] [Err]: Exception in thread Thread-32919:
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:12:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:12:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:12:42 2019] [Err]:     self.run()
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 55, in <lambda>
[Thu Oct 17 14:12:42 2019] [Err]:     Thread(None, lambda: self.background.cleanup_bubs()).start()
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 114, in cleanup_bubs
[Thu Oct 17 14:12:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:12:42 2019] [Err]:     x, y, = get_coords(self._canvas, self.__bubbles[index])
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 55, in <lambda>
[Thu Oct 17 14:12:42 2019] [Err]: Exception in thread Thread-11510:
[Thu Oct 17 14:12:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:12:42 2019] [Err]: IndexError: list index out of range
[Thu Oct 17 14:12:42 2019] [Err]:     Thread(None, lambda: self.background.cleanup_bubs()).start()
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 114, in cleanup_bubs
[Thu Oct 17 14:12:42 2019] [Err]: 
[Thu Oct 17 14:12:42 2019] [Err]:     x, y, = get_coords(self._canvas, self.__bubbles[index])
[Thu Oct 17 14:12:42 2019] [Err]:     self.run()
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:12:42 2019] [Err]: IndexError: list index out of range
[Thu Oct 17 14:12:42 2019] [Err]: 
[Thu Oct 17 14:12:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 55, in <lambda>
[Thu Oct 17 14:12:42 2019] [Err]:     Thread(None, lambda: self.background.cleanup_bubs()).start()
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 114, in cleanup_bubs
[Thu Oct 17 14:12:42 2019] [Err]:     x, y, = get_coords(self._canvas, self.__bubbles[index])
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\utils\__init__.py", line 21, in get_coords
[Thu Oct 17 14:12:42 2019] [Err]:     x = (pos[0] + pos[2]) / 2
[Thu Oct 17 14:12:42 2019] [Err]: IndexError: list index out of range
[Thu Oct 17 14:12:42 2019] [Err]: 
[Thu Oct 17 14:12:42 2019] [Err]: Exception in thread Thread-33494:
[Thu Oct 17 14:12:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:12:42 2019] [Err]:     self.run()
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:12:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 55, in <lambda>
[Thu Oct 17 14:12:42 2019] [Err]:     Thread(None, lambda: self.background.cleanup_bubs()).start()
[Thu Oct 17 14:12:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 114, in cleanup_bubs
[Thu Oct 17 14:12:42 2019] [Err]:     x, y, = get_coords(self._canvas, self.__bubbles[index])
[Thu Oct 17 14:12:42 2019] [Err]: IndexError: list index out of range
[Thu Oct 17 14:12:42 2019] [Err]: 
[Thu Oct 17 14:12:44 2019] [Out]: Quit
