[Thu Oct 17 14:14:01 2019] [Out]: Args: ['C:/Users/quint/Documents/GitHub/QplayBubbles-Releaes/__main__.py', 'v1.5.1-pre5', 'v1_5_1_pre5', '16']
[Thu Oct 17 14:14:01 2019] [Out]: Launcher Path: C:\Users\quint\Documents
[Thu Oct 17 14:14:01 2019] [Out]: {'bubble': {'chance': 10, 'max-radius': 30, 'min-radius': 21, 'max-speed': 4.8, 'base-speed': 4.8, 'screen-gap': 100}, 'game': {'level-score': 10000, 'time-limit': 90, 'pause': False, 'resolution': '1920x1080', 'ship-radius': 15, 'ship-speed': 10, 'fullscreen': True, 'language': 'en'}, 'font': {'family': 'helvetica', 'size': -9}}
[Thu Oct 17 14:14:03 2019] [Err]: Exception in thread Thread-4344:
[Thu Oct 17 14:14:03 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:14:03 2019] [Err]:     self.run()
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:14:03 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 14:14:03 2019] [Err]: Exception in thread Thread-4432:
[Thu Oct 17 14:14:03 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 14:14:03 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:14:03 2019] [Err]: Exception in thread Thread-4494:
[Thu Oct 17 14:14:03 2019] [Out]: Quit[Thu Oct 17 14:14:03 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 102, in create_bubble
[Thu Oct 17 14:14:03 2019] [Err]:     self.__bubbles.append(self._canvas.create_oval(x - r, y - r, x + r, y + r, outline="white"))
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner

[Thu Oct 17 14:14:03 2019] [Err]:     self.run()
[Thu Oct 17 14:14:03 2019] [Err]:     self.run()
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2495, in create_oval
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:14:03 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:14:03 2019] [Err]:     return self._create('oval', args, kw)
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 14:14:03 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 2480, in _create
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 14:14:03 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 14:14:03 2019] [Err]:     *(args + self._options(cnf, kw))))
[Thu Oct 17 14:14:03 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 98, in create_bubble
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 98, in create_bubble
[Thu Oct 17 14:14:03 2019] [Err]:     y = randint(int(r), int(self._canvas.winfo_height() - r))
[Thu Oct 17 14:14:03 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:14:03 2019] [Err]:     y = randint(int(r), int(self._canvas.winfo_height() - r))
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1000, in winfo_height
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1000, in winfo_height
[Thu Oct 17 14:14:03 2019] [Err]:     self.tk.call('winfo', 'height', self._w))
[Thu Oct 17 14:14:03 2019] [Err]:     raise result
[Thu Oct 17 14:14:03 2019] [Err]:     self.tk.call('winfo', 'height', self._w))
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 71, in <lambda>
[Thu Oct 17 14:14:03 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:14:03 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:14:03 2019] [Err]:     self.call_tk_attr_threadsafe(_f, *a, **kw))
[Thu Oct 17 14:14:03 2019] [Err]: _tkinter.TclError: invalid command name ".!canvas"
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 88, in call_tk_attr_threadsafe
[Thu Oct 17 14:14:03 2019] [Err]:     raise result
[Thu Oct 17 14:14:03 2019] [Err]:     raise result
[Thu Oct 17 14:14:03 2019] [Err]: 
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:14:03 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\site-packages\threadsafe_tkinter\__init__.py", line 133, in process_requests
[Thu Oct 17 14:14:03 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:14:03 2019] [Err]:     response[:] = (func(*a, **kw), False)
[Thu Oct 17 14:14:03 2019] [Err]: _tkinter.TclError: bad window path name ".!canvas"
[Thu Oct 17 14:14:03 2019] [Err]: _tkinter.TclError: bad window path name ".!canvas"
[Thu Oct 17 14:14:03 2019] [Err]: 
[Thu Oct 17 14:14:03 2019] [Err]: 
