[Tue Feb 11 11:20:06 2020] [Out]: Args: ['G:/Code/QplayBubbles-Releaes/__init__.py']
[Tue Feb 11 11:20:06 2020] [Err]: Traceback (most recent call last):
[Tue Feb 11 11:20:06 2020] [Err]:   File "G:/Code/QplayBubbles-Releaes/__init__.py", line 91, in <module>
[Tue Feb 11 11:20:06 2020] [Err]:     launcher_cfg = {"version": sys.argv[1],
[Tue Feb 11 11:20:06 2020] [Err]: IndexError: list index out of range
